try {
  document.querySelector('.standings tbody tr th:nth-of-type(2)').style.width='200px';
} catch (error) {
  console.error(error);
}

const dict = {'Sr_lucky_MaN':'Дунин Дмитрий 10В',
'Ivanov_Slava':'Иванов Вячеслав 10В',
'MillerEA':'Миллер Евгений 10В',
'Anastasia_36725':'Поздина Анастасия 10В',
'mikantrop':'Антропов Михаил 10Е',
'barabula':'Бабайлов Максим 10Е',
'ZMEME2009':'Баталов Михаил 10Е',
'ArtBUrCOP':'Беляков Артем 10Е',
'theWeird0':'Бурыкина Ксения 10Е',
'n30c0rtoxes':'Гусев Александр 10Е',
'g1ngerxvx':'Долгополова Ирина 10Е',
'kanev':'Канев Иван 10Е',
'ArseniyLeontev':'Леонтьев Арсений 10Е',
'chelovek583':'Мамонова Полина 10Е',
'DankeMart':'Мартиросов Даниил 10Е',
'mslava':'Мартынов Вячеслав 10Е',
'MariaHuanovna':'Можегоров Андрей 10Е',
'Muravev':'Муравьев Дмитрий 10Е',
'slavik-mozhet':'Насыров Савва 10Е',
'ZalenoToTo':'Селезнёв Александр 10Е',
'Gleb_Skovorodnikov':'Сковородников Глеб 10Е',
'IlonMask':'Соснин Илья 10Е',
'Reveek':'Сочнев Даниил 10Е',
'Yutkin_A':'Юткин Александр 10Е',
'vovchan':'	Куриннов Владимир  10Н',
'grmmmely':'Гурьев Роман  10Н',
'Vsevolod_progr':'Кондрашин Всеволод 10Н',
'Amogus2.':'Магазов Артур 10Н',
'7hhhh':'Найдёнов Ярослав 10Н',
'makar07':'Хренников Макар 10Н',
'asharaev':'Шараев Андрей 10Н',
'mlovbnee':'Щепарева Мария 10Н',
'KVL':'Лихачев Константин 11В',
'GlebNechaev':'Нечаев Глеб 11В',
'KingArthurTheGreat':'Хримян Артур 11Г',
'VanyaM1':'Мельников Иван 11Д',
'grigalex40':'Алексеев Григорий 11Е',
'InnaAlekseeva':'Алексеева Инна 11Е',
'thermos':'Бавыкин Артур 11Е',
'Mrlime':'Бибиков Максим 11Е',
'Sparr0w':'Бутенко Игорь 11Е',
'semwin2008':'Виноградов Семен 11Е',
'Alex_VAA':'Волков Алексей 11Е',
'deterraleon':'Волохов Иван 11Е',
'goodsoul_a':'Добряк Артем 11Е',
'vanta5n':'Долгова Таисия 11Е',
'Wileyne':'Знышев Дмитрий 11Е',
'veliak':'Кайль Лев 11Е',
'KotlechkovEgor':'Котлечков Егор 11Е',
'Lihach':'Лихачев Иван 11Е',
'Ghuiko':'Нурисламов Владислав 11Е',
'Foks':'Печёнкина Василиса 11Е',
'NeNichiy':'Рогожин Константин 11Е',
'VictorS':'Свалов Виктор 11Е',
'asdasdafg':'Шиканов Савва 11Е',
'AdunAdunov':'Ширкунов Евгений 11Е',
'gasnikova_anya':'Гасникова Анна  11И',
'bebrochkas':'Попыванов Даниил  11И',
'nastyagrebneva':'Гребнева Анастасия 11Н',
'Alexunder9':'Девятов Александр 11Н',
'kefip':'Дымшаков Константин 11Н',
'Moksha1352':'Лазарев Михаил 11Н',
'grandgaev':'Нугаев Василий 11Н',
'ivan_ovs':'Овсянников Иван 11Н',
'amlet00':'Окулов Никита 11Н',
'viuver':'Романов Владислав 11Н',
'razetheking':'Файзрахманов Олег 11Н',
'finich':'Бабушкин Артём 8Е',
'trokk60':'Дюндин Андрей  8Е',
'4eloVeeek_C_umeHem':'Сорокин Степан  8Е',
'Stepanal':'Бобыкин Степан 9В',
'leokostromin':'Костромин Леонид 9В',
'Mixail_xap':'Харитонов Михаил 9В',
'nikitasplace':'Богданов Никита 9Е',
'Lakant':'Канторович Лев 9Е',
'WaterCeiling65':'Коркин Никита  9Е',
'korobeynikov.p.i':'Коробейников Павел 9Е',
'Datym':'Матвеев Иван 9Е',
'Ivan_qwertyu':'Микрюков Иван 9Е',
'Kyzia':'Назаров Анатолий 9Е',
'Redk1tli':'Добразов Максим гимн9',
'yeey71':'Закиров Егор гимн9',
'awrt_xz':'Канатова Вера гимн9',
'BentTick':'Куделин Максим гимн9',
'acadec':'Мариева Ульяна гимн9',
'Duxa':'Свистунов Андрей гимн9',
'pon':'Суханов Артемий гимн9',
'k4m4lov':'Камалов Артём губ.лицей',
'Levonciy':'Нестеров Лев губ.лицей',
'MiniBess':'Бессолицын Кирилл ',
'gripju':'Васильев Вадим ',
'MrFazer':'Гончаров Константин ',
'MaksimXD':'Дюндин Максим ',
'Maxython':'Ерогов Максим ',
'zhiganov_v':'Жиганов Владислав ',
'Friendiks':'Ипатов Андрей ',
'kiriakaz':'Казанцев Кирилл ',
'RomaKar':'Карсаков Роман ',
'Mairon2093':'Корнеева Мария ',
'alexveark3':'Краев Александр ',
'andreyveark':'Краев Андрей ',
'ksof_sk':'Кудашева София ',
'Yassia':'Куликова Ярослава ',
'Klauss':'Куценко Евгений ',
'IgorLipin123':'Липин Игорь ',
'n1ret':'Логинов Олег ',
'adrony':'Мамедов Артем ',
'Demyan987':'Оболдин Демьян ',
'Fedor69':'Платонов Федор ',
'Davidrol':'Пономарев Давид ',
'irlenp':'Попов Леонид ',
'im_sad_now':'Рожкова Полина ',
'vbnz_miteo':'Сахарлинский Дмитрий ',
'Topaz2090':'Ступин Дмитрий ',
'TROFI':'Устьянцев Трофим ',
'Gemefoll':'Фефилов Егор ',
'andfey':'Филиппов Андрей ',
'lewc':'Цыбань Лев',
 'Neem_Ko':'Александров Михаил 8Е',
'msensation':'Середа Мария 10Н',
'Sanec1hek1':'Сазонов Александр 8Е',
'evgeniam999':'Харитонов Иван 9Е',
'Vlamir':'Булычев Владимир 8Е',
'zlata.si':'Бугаев Кирилл 8Е',
'Osipovsaha':'Осипов Александр 10Н',
'DimaGhost':'Присяжнюк Дмитрий 10Н',
'chelovek5556':'Осипова Алиса 10Н',
'Nikolai_Khr':'Храмцов Николай 10Н',
'grisha0342':'Воронов Григорий 10Н',
 'ladas27':'Устюгов Тимофей 10Н',
'art333':'Верходанов Артемий 8Е',
'Diana_Shneider':'Шнейдер Диана 9Е',
'nas_tyyy':'Лукьянова Анастасия 9Е',
'Mr.Root.':'Быкова Светлана 10С',
'ivanporotov':'Поротов Иван 9Е',
              'Remargoo':'Наумович Кирилл',
              '<span class="legendary-user-first-letter">R</span>emargoo':'Наумович Кирилл',
              'YUPIYO':'Шаранков Михаил',
              'chamberzsut':'Леонов Алексей',
              'Slend32':'Романов Савелий',
              'timofey_sav':'Савицкий Тимофей',
              'HollowVlad':'Зайцев Владислав',
              'fo_patria':'fo_patria',
              'Potom':'Белокуров Тимофей',
              'K0JI6G1-1GB_JIew':'Колбенев Лев'
              
};

// Rename users
document.querySelectorAll('.rated-user').forEach(a => {
  const key = a.innerHTML.trim();
  if (key in dict) {
    a.innerHTML = dict[key];
  }
});

// Hide flag
document.querySelectorAll('.standings-flag').forEach(a => {
  a.remove();
});

// Hide to-practice
const aElements = document.querySelectorAll('.change-participant-type-link').forEach(a => {
  a.remove()
});


