try {
  document.querySelector('.standings tbody tr th:nth-of-type(2)').style.width='200px';
} catch (error) {
  console.error(error);
}

const dict = {330	Ярослав Найдёнов	'330':'Ярослав Найдёнов',
7hhhh	Найдёнов Ярослав	'7hhhh':'Найдёнов Ярослав',
a_ok	Кривощекова Евгения Антоновна	'a_ok':'Кривощекова Евгения Антоновна',
acadec	Мариева Ульяна	'acadec':'Мариева Ульяна',
Adfrand	Шатковский Александр Нижневартовск	'Adfrand':'Шатковский Александр Нижневартовск',
adrony	Мамедов Артем 130	'adrony':'Мамедов Артем 130',
AdunAdunov	Ширкунов Евгений 10Е	'AdunAdunov':'Ширкунов Евгений 10Е',
afkfishka	Никитенко Игорь Нижневартовск	'afkfishka':'Никитенко Игорь Нижневартовск',
aleksandrmak1207	Маккавеев Александр	'aleksandrmak1207':'Маккавеев Александр',
Alex_VAA	Волков Алексей 10Е	'Alex_VAA':'Волков Алексей 10Е',
Alexunder9	Девятов Александр 10Н	'Alexunder9':'Девятов Александр 10Н',
alexveark3	Краев Александр	'alexveark3':'Краев Александр',
amlet00	Окулов Никита 10Н	'amlet00':'Окулов Никита 10Н',
Amogus2.	Магазов Артур Ренатович	'Amogus2.':'Магазов Артур Ренатович',
andbel	Белоусов Андрей	'andbel':'Белоусов Андрей',
andfey	Филиппов Андрей	'andfey':'Филиппов Андрей',
ANDREYkao__	Кулаков Андрей 11Н	'ANDREYkao__':'Кулаков Андрей 11Н',
andreyveark	Краев Андрей	'andreyveark':'Краев Андрей',
anotherflowerrotten	Ермаков Роман	'anotherflowerrotten':'Ермаков Роман',
ArseniyLeontev	Леонтьев Арсений 9Е	'ArseniyLeontev':'Леонтьев Арсений 9Е',
Arsenyi123	Рабовлюк Арсений 10Н	'Arsenyi123':'Рабовлюк Арсений 10Н',
ArtBUrCOP	Беляков Артем 9Е	'ArtBUrCOP':'Беляков Артем 9Е',
artem_galimulin	Галимулин Артем 11В	'artem_galimulin':'Галимулин Артем 11В',
artem_zelenkin	Зеленкин Артем 11Е	'artem_zelenkin':'Зеленкин Артем 11Е',
asdasdafg	Шиканов Савва 10Е	'asdasdafg':'Шиканов Савва 10Е',
asharaev	Шараев Андрей	'asharaev':'Шараев Андрей',
awrt_xz	Канатова Вера	'awrt_xz':'Канатова Вера',
barabula	Бабайлов Максим 9Е	'barabula':'Бабайлов Максим 9Е',
BentTick	BentTick ??	'BentTick':'BentTick ??',
Blazee	Сажин Андрей Нижневартовск	'Blazee':'Сажин Андрей Нижневартовск',
bot_angeldust	Силкин Тимофей 11Н	'bot_angeldust':'Силкин Тимофей 11Н',
BottleOfJuice	Бессолицын Максим 11Е	'BottleOfJuice':'Бессолицын Максим 11Е',
bug00n	Тулгаев Данил 11Н	'bug00n':'Тулгаев Данил 11Н',
chelovek583	Мамонова Полина 9Е	'chelovek583':'Мамонова Полина 9Е',
Danchik7	Яковлев Даниил 11В	'Danchik7':'Яковлев Даниил 11В',
Daniik2	Назаров Данил Нижневартовск	'Daniik2':'Назаров Данил Нижневартовск',
Danil18	Мищенко Данила Нижневартовск	'Danil18':'Мищенко Данила Нижневартовск',
DankeMart	Мартиросов Даниил 9Е	'DankeMart':'Мартиросов Даниил 9Е',
Datym	Матвеев Иван	'Datym':'Матвеев Иван',
Davidrol	Пономарев Давид	'Davidrol':'Пономарев Давид',
Demyan987	Оболдин Демьян Андреевич	'Demyan987':'Оболдин Демьян Андреевич',
den0620	Дубовик Денис 11Е	'den0620':'Дубовик Денис 11Е',
deterraleon	Волохов Иван 10Е	'deterraleon':'Волохов Иван 10Е',
Drunk_Squirrel	Суханов Артемий Глебович	'Drunk_Squirrel':'Суханов Артемий Глебович',
DudeG	Дудин Георгий	'DudeG':'Дудин Георгий',
Duxa	Свистунов Андрей	'Duxa':'Свистунов Андрей',
dzhlma	Калугин Дмитрий 11Н	'dzhlma':'Калугин Дмитрий 11Н',
Fedor69	Платонов Федор	'Fedor69':'Платонов Федор',
finich	Бабушкин Артём	'finich':'Бабушкин Артём',
Foks	Печёнкина Василиса 10Е	'Foks':'Печёнкина Василиса 10Е',
Friendiks	Ипатов Андрей 10Е	'Friendiks':'Ипатов Андрей 10Е',
g1ngerxvx	Долгополова Ирина 9Е	'g1ngerxvx':'Долгополова Ирина 9Е',
Gemefoll	Фефилов Егор	'Gemefoll':'Фефилов Егор',
Ghuiko	Нурисламов Владислав 10Е	'Ghuiko':'Нурисламов Владислав 10Е',
Gleb_Skovorodnikov	Сковородников Глеб 9Е	'Gleb_Skovorodnikov':'Сковородников Глеб 9Е',
glebch	Черноморцев Глеб	'glebch':'Черноморцев Глеб',
GlebNechaev	Нечаев Глеб 10В	'GlebNechaev':'Нечаев Глеб 10В',
gnominokentiy	Стафеев Федор 11В	'gnominokentiy':'Стафеев Федор 11В',
goodsoul_a	Добряк Артем	'goodsoul_a':'Добряк Артем',
Gosha111	Водяный Георгий 11И	'Gosha111':'Водяный Георгий 11И',
grandgaev	Нугаев Василий 10Н	'grandgaev':'Нугаев Василий 10Н',
grigalex40	Алексеев Григорий 10Е	'grigalex40':'Алексеев Григорий 10Е',
I3eg1nner	Пеганов Илья	'I3eg1nner':'Пеганов Илья',
IgorLipin123	Липин Игорь	'IgorLipin123':'Липин Игорь',
IlonMask	Соснин Илья 9Е	'IlonMask':'Соснин Илья 9Е',
im_sad_now	Рожкова Полина	'im_sad_now':'Рожкова Полина',
InnaAlekseeva	Алексеева Инна 10Е	'InnaAlekseeva':'Алексеева Инна 10Е',
irlenp	Попов Леонид 35 гимн	'irlenp':'Попов Леонид 35 гимн',
ivan_ovs	Овсянников Иван 10Н	'ivan_ovs':'Овсянников Иван 10Н',
Ivan_qwertyu	Микрюков Иван 8Е	'Ivan_qwertyu':'Микрюков Иван 8Е',
Ivanov_Slava	Иванов Вячеслав 9В	'Ivanov_Slava':'Иванов Вячеслав 9В',
ivchenkoandrey2	Ивченко Андрей 11Е	'ivchenkoandrey2':'Ивченко Андрей 11Е',
JabaJaba_v.2.0	Белай Константин 11Н	'JabaJaba_v.2.0':'Белай Константин 11Н',
janekri	Кривощекова Евгения 11Н	'janekri':'Кривощекова Евгения 11Н',
k4m4lov	Камалов Артём Маратович	'k4m4lov':'Камалов Артём Маратович',
kanev	Канев Иван 9Е	'kanev':'Канев Иван 9Е',
kefip	Дымшаков Константин 10Н	'kefip':'Дымшаков Константин 10Н',
Kicel_007	Стрижов Николай	'Kicel_007':'Стрижов Николай',
KingArthurTheGreat	Хримян Артур	'KingArthurTheGreat':'Хримян Артур',
kiriakaz	Казанцев Кирилл	'kiriakaz':'Казанцев Кирилл',
Konobeitsev_Ivan	Конобейцев Иван	'Konobeitsev_Ivan':'Конобейцев Иван',
korobeynikov.p.i	Коробейников Павел 8Е	'korobeynikov.p.i':'Коробейников Павел 8Е',
KoStTeFaG	Овчинников Константин 11Е	'KoStTeFaG':'Овчинников Константин 11Е',
KotlechkovEgor	Котлечков Егор 10Е	'KotlechkovEgor':'Котлечков Егор 10Е',
ksof_sk	Кудашева София	'ksof_sk':'Кудашева София',
KVL	Лихачев Константин 10В	'KVL':'Лихачев Константин 10В',
Kyzia	Назаров Анатолий	'Kyzia':'Назаров Анатолий',
leokostromin	Костромин Леонид 8В	'leokostromin':'Костромин Леонид 8В',
levonciy	Нестеров Лев	'levonciy':'Нестеров Лев',
lewc	Цыбань Лев	'lewc':'Цыбань Лев',
Lihach	Лихачев Иван 10Е	'Lihach':'Лихачев Иван 10Е',
lp_sty	lp_sty ??	'lp_sty':'lp_sty ??',
lucky_MaNchik	Дунин Дмитрий 9В	'lucky_MaNchik':'Дунин Дмитрий 9В',
Mairon2093	Корнеева Мария	'Mairon2093':'Корнеева Мария',
makar07	Хренников Макар	'makar07':'Хренников Макар',
MaksimXD	Дюндин Максим	'MaksimXD':'Дюндин Максим',
Mamba_AI	Илларионов Артем 11Н	'Mamba_AI':'Илларионов Артем 11Н',
MariaHuanovna	Можегоров Андрей 9Е	'MariaHuanovna':'Можегоров Андрей 9Е',
Maxython	Ерогов Максим	'Maxython':'Ерогов Максим',
mikantrop	Антропов Михаил 9Е	'mikantrop':'Антропов Михаил 9Е',
MillerEA	Миллер Евгений	'MillerEA':'Миллер Евгений',
MiniBess	Бессолицын Кирилл 9В	'MiniBess':'Бессолицын Кирилл 9В',
Mixail_xap	Харитонов Михаил 8В	'Mixail_xap':'Харитонов Михаил 8В',
mlovbnee	Щепарева Мария	'mlovbnee':'Щепарева Мария',
Moksha1352	Лазарев Михаил	'Moksha1352':'Лазарев Михаил',
Morr66	Букин Ярослав 11Е	'Morr66':'Букин Ярослав 11Е',
MrFazer	Гончаров Константин	'MrFazer':'Гончаров Константин',
Mrlime	Бибиков Максим 10Е	'Mrlime':'Бибиков Максим 10Е',
mslava	Мартынов Вячеслав 9Е	'mslava':'Мартынов Вячеслав 9Е',
Muravev	Муравьев Дмитрий 9Е	'Muravev':'Муравьев Дмитрий 9Е',
n1ret	Логинов Олег Алексеевич	'n1ret':'Логинов Олег Алексеевич',
n30c0rtoxes	Гусев Александр 9Е	'n30c0rtoxes':'Гусев Александр 9Е',
nastyagrebneva	Гребнева Анастасия 10Н	'nastyagrebneva':'Гребнева Анастасия 10Н',
Nekrasovmaksim	Некрасов Максим 11Н	'Nekrasovmaksim':'Некрасов Максим 11Н',
NeNichiy	Рогожин Константин 10Е	'NeNichiy':'Рогожин Константин 10Е',
nicky2	Дубских Николай	'nicky2':'Дубских Николай',
nikitasplace	Богданов Никита 8Е	'nikitasplace':'Богданов Никита 8Е',
Nosok_Sudjbi	Малинин Павел 11Н	'Nosok_Sudjbi':'Малинин Павел 11Н',
Orlenko__Igor0	Орленко Игорь 11Е	'Orlenko__Igor0':'Орленко Игорь 11Е',
p1k	Кондратьев Игорь	'p1k':'Кондратьев Игорь',
p1t	Козлов Петр	'p1t':'Козлов Петр',
pon	Суханов Артемий	'pon':'Суханов Артемий',
pooo07	Козлова Полина	'pooo07':'Козлова Полина',
Potom	Белокуров Тимофей Нижневартовск	'Potom':'Белокуров Тимофей Нижневартовск',
razetheking	Файзрахманов Олег	'razetheking':'Файзрахманов Олег',
Redk1tli	Добразов Максим	'Redk1tli':'Добразов Максим',
Reveek	Сочнев Даниил 9Е	'Reveek':'Сочнев Даниил 9Е',
RomaKar	Карсаков Роман	'RomaKar':'Карсаков Роман',
selleproyt	Соколов Артур 11Н	'selleproyt':'Соколов Артур 11Н',
semenchenko	Семенченко Никита	'semenchenko':'Семенченко Никита',
semenovad	Семенова Дарья Нижневартовск	'semenovad':'Семенова Дарья Нижневартовск',
semwin2008	Виноградов Семен 10Е	'semwin2008':'Виноградов Семен 10Е',
Ser07math	Ращупкин Сергей Нижневартовск	'Ser07math':'Ращупкин Сергей Нижневартовск',
shusha44	Шебалина Алиса 11Е	'shusha44':'Шебалина Алиса 11Е',
skeletonah	Чагин Дмитрий	'skeletonah':'Чагин Дмитрий',
slavik-mozhet	Насыров Савва 9Е	'slavik-mozhet':'Насыров Савва 9Е',
Sparr0w	Бутенко Игорь 10Е	'Sparr0w':'Бутенко Игорь 10Е',
standoff_player	Воропаев Арсений 11Н	'standoff_player':'Воропаев Арсений 11Н',
Stepanal	Бобыкин Степан 8В	'Stepanal':'Бобыкин Степан 8В',
Subio	Цевилев Матвей	'Subio':'Цевилев Матвей',
thermos	Бавыкин Артур 10Е	'thermos':'Бавыкин Артур 10Е',
theWeird0	Бурыкина Ксения 9Е	'theWeird0':'Бурыкина Ксения 9Е',
Topaz2090	Ступин Дмитрий	'Topaz2090':'Ступин Дмитрий',
TROFI	Устьянцев Трофим	'TROFI':'Устьянцев Трофим',
uliana_kaffeetrinker	Диколенко Ульяна 9А	'uliana_kaffeetrinker':'Диколенко Ульяна 9А',
vakfa	Кодес Михаил	'vakfa':'Кодес Михаил',
vanta5n	Долгова Таисия 10Е	'vanta5n':'Долгова Таисия 10Е',
VanyaM1	Мельников Иван 10Д	'VanyaM1':'Мельников Иван 10Д',
vdv09	Бугрышев Михаил	'vdv09':'Бугрышев Михаил',
veliak	Кайль Лев 10Е	'veliak':'Кайль Лев 10Е',
VictorS	Свалов Виктор 10Е	'VictorS':'Свалов Виктор 10Е',
viuver	Романов Владислав 10Н	'viuver':'Романов Владислав 10Н',
vpanfilov	Панфилов Василий 11Н	'vpanfilov':'Панфилов Василий 11Н',
Vsevolod_progr	Кондрашин Всеволод 9Г	'Vsevolod_progr':'Кондрашин Всеволод 9Г',
Wileyne	Знышев Дмитрий 10Е	'Wileyne':'Знышев Дмитрий 10Е',
Yassia	Куликова Ярослава 10Е	'Yassia':'Куликова Ярослава 10Е',
yeey71	Закиров Егор	'yeey71':'Закиров Егор',
yershovdmitriy	Ершов Дмитрий	'yershovdmitriy':'Ершов Дмитрий',
YseraKon	Коновалов Ярослав 11В	'YseraKon':'Коновалов Ярослав 11В',
Yutkin_A	Юткин Александр 9Е	'Yutkin_A':'Юткин Александр 9Е',
ZalenoToTo	Селезнёв Александр 9Е	'ZalenoToTo':'Селезнёв Александр 9Е',
zhiganov_v	Жиганов Владислав	'zhiganov_v':'Жиганов Владислав',
ZMEME2009	Баталов Михаил 9Е	'ZMEME2009':'Баталов Михаил 9Е',
              
};

// Rename users
document.querySelectorAll('.rated-user').forEach(a => {
  const key = a.innerHTML.trim();
  if (key in dict) {
    a.innerHTML = dict[key];
  }
});

// Hide flag
document.querySelectorAll('.standings-flag').forEach(a => {
  a.remove();
});

// Hide to-practice
const aElements = document.querySelectorAll('.change-participant-type-link').forEach(a => {
  a.remove()
});
